# Generated by Django 2.0.13 on 2019-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padminiBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myphoto',
            field=models.ImageField(default='padminiBlog/images/already.png', upload_to='padminiBlog/images'),
        ),
    ]
