# Generated by Django 2.0.13 on 2019-05-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padminiBlog', '0002_post_myphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='myphoto',
        ),
    ]
